FROM apache/hive:4.0.0

# Add S3A support for Hive Metastore so it can create/read Iceberg warehouse on MinIO
RUN mkdir -p /opt/hive/auxlib \
    && curl -L -o /opt/hive/auxlib/hadoop-aws-3.3.4.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
    && curl -L -o /opt/hive/auxlib/aws-java-sdk-bundle-1.12.262.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

ENV HIVE_AUX_JARS_PATH=/opt/hive/auxlib
